#!/usr/bin/env python3
"""Generates desktop/libgfx/font_data.c from desktop/libgfx/font.txt.

Usage: tools/mkfont.py [--check]
  --check  fail (exit 1) if font_data.c is not what font.txt generates;
           `make test` runs this, so the two cannot drift apart.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "desktop", "libgfx", "font.txt")
OUTPUT = os.path.join(ROOT, "desktop", "libgfx", "font_data.c")
ROWS, WIDTH = 9, 5


def parse(text):
    glyphs = {}
    lines = [l.rstrip("\n") for l in text.splitlines()]
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.startswith("#"):
            i += 1
            continue
        if not line.startswith("@ "):
            sys.exit(f"font.txt:{i + 1}: expected a '@' block header")
        names = line[2:].split(" ")
        chars = [" " if n == "space" else n for n in names]
        if any(len(c) != 1 for c in chars):
            sys.exit(f"font.txt:{i + 1}: names must be single characters or 'space'")
        rows = lines[i + 1:i + 1 + ROWS]
        if len(rows) != ROWS:
            sys.exit(f"font.txt:{i + 1}: a block needs {ROWS} rows")
        for r, row in enumerate(rows):
            groups = row.split(" ")
            if len(groups) != len(chars) or any(len(g) != WIDTH or set(g) - set(".#") for g in groups):
                sys.exit(f"font.txt:{i + 2 + r}: expected {len(chars)} groups of {WIDTH} '.'/'#'")
        for k, c in enumerate(chars):
            if c in glyphs:
                sys.exit(f"font.txt:{i + 1}: {c!r} defined twice")
            glyphs[c] = [row.split(" ")[k] for row in rows]
        i += 1 + ROWS
    missing = [chr(c) for c in range(0x20, 0x7F) if chr(c) not in glyphs]
    if missing:
        sys.exit(f"font.txt: missing glyphs for {''.join(missing)!r}")
    return glyphs


def generate(glyphs):
    out = ["/* Generated by tools/mkfont.py from font.txt -- edit that, not this. */",
           '#include "gfx.h"', "",
           "/* Printable ASCII from ' '; each row's 5 pixels are bits 4..0. */",
           f"const uint8_t gfx_font[95][{ROWS}] = {{"]
    for code in range(0x20, 0x7F):
        c = chr(code)
        values = ", ".join(f"0x{int(row.replace('#', '1').replace('.', '0'), 2):02x}"
                           for row in glyphs[c])
        shown = {"\\": "backslash", "'": "quote"}.get(c, c)
        out.append(f"\t{{ {values} }}, /* {shown} */")
    out.append("};")
    return "\n".join(out) + "\n"


def main():
    with open(SOURCE) as f:
        text = generate(parse(f.read()))
    if "--check" in sys.argv:
        with open(OUTPUT) as f:
            if f.read() != text:
                sys.exit("font_data.c is out of date: run tools/mkfont.py")
        print("PASS: font_data.c matches font.txt")
        return
    with open(OUTPUT, "w") as f:
        f.write(text)


if __name__ == "__main__":
    main()
